version: "2"
services:
  app:
    build: ./app
    env_file: database.conf
    links:
      - db
    ports:
      - 8080:8080

  db:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
